### PR TITLE
Added project.m

### PR DESCRIPTION
**Pull request by yicheng0922**
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/optimized-compliance/3)

### CODE REVIEW

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[matlab/project.m, line 22 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVx2JVJa53Aswq-R-WB:-KVx2JVKctpcpddc927g:bza7y1s) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e36eeab8e88990d3c06219c1272e9702a47014a9/matlab/project.m#L22)):_

> ``` objc
>     alpha = box.alpha;
> 
>     % setting up box vertices
> ```

I've seen these lines of code before. If you're using a piece of code twice, stick that code into a single function. Then you only have to debug or update the code once!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[matlab/project.m, line 3 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVx2cx67BcuU7s2oR4S:-KVx2cx67BcuU7s2oR4T:bsmag3c) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e36eeab8e88990d3c06219c1272e9702a47014a9/matlab/project.m#L3)):_

> ``` objc
> function [ min_dot, max_dot ] = project( shape, axis )
> % This function projects 'shape' onto the given axis.
> % When shape is a box (isRect = true), the vertex (EMD: which vertex) will be 
> ```

My comment before said (EMD: which vertex) and my question remains: which vertex?

---

_[matlab/project.m, line 5 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVx2l7byjBimMoIrFcM:-KVx2l7byjBimMoIrFcN:bnaerf) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e36eeab8e88990d3c06219c1272e9702a47014a9/matlab/project.m#L5)):_

> ``` objc
> % When shape is a box (isRect = true), the vertex (EMD: which vertex) will be 
> % projected. 
> % when shape is a sector (isRect = false), the center, the end points of
> ```

BTW This is a good piece of documentation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by yicheng0922** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[matlab/project.m, line 3 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVx2cx67BcuU7s2oR4S:-KVx5AnOn9Xn8UkZX7lf:b-756w4j) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e36eeab8e88990d3c06219c1272e9702a47014a9/matlab/project.m#L3)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> My comment before said (EMD: which vertex) and my question remains: which vertex?
> </details>
> Changed comment to "all four vertices"

---

_[matlab/project.m, line 22 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVx2JVJa53Aswq-R-WB:-KVx5HueaJdcTyRFgoyU:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e36eeab8e88990d3c06219c1272e9702a47014a9/matlab/project.m#L22)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> I've seen these lines of code before. If you're using a piece of code twice, stick that code into a single function. Then you only have to debug or update the code once!
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

_[matlab/compute_box_vertices.m, line 9 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzLo79qTrQ-UypStU8:-KVzLo7AokkG4n8JHfNG:b7qeatr) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/compute_box_vertices.m#L9)):_

> ``` objc
> %           w: the width of the box
> %           h: the height of the box 
> %           alpha: the orientation of the box represented by a 2d angle in 
> ```

It's the "2D orientation" of the box, angle is not 2D!

---

_[matlab/compute_box_vertices.m, line 19 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzLVHDtkuosz_Qt6S9:-KVzLVHDtkuosz_Qt6SA:bpyl315) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/compute_box_vertices.m#L19)):_

> ``` objc
>     alpha = box.alpha;
> 
>     % setting up box vertices
> ```

Gerund issue.

---

_[matlab/project.m, line 27 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMN1yjXmg37i3wFjL:-KVzMN1yjXmg37i3wFjM:b-hdl36j) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L27)):_

> ``` objc
>     vertices_world = [x, x+radius*cos(alpha1), x+radius*cos(alpha2); y, y+radius*sin(alpha1), y+radius*sin(alpha2)];
> 
>     % check if the line parallel to axis and crosses the center intersescts
> ```

crosses -> crossing?

---

_[matlab/project.m, line 28 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMPcmD7xHB8P3wv7v:-KVzMPcnNQpCscLvFD_2:bg79gof) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L28)):_

> ``` objc
> 
>     % check if the line parallel to axis and crosses the center intersescts
>     % the arc, if true, the intersection need to be added. This is done by
> ```

need -> needs"

---

_[matlab/project.m, line 31 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMe5vrORp3F_Fsohr:-KVzMe5vrORp3F_Fsohs:b6056sa) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L31)):_

> ``` objc
>     % checking if the axis is pointing to a direction between alpha1 and
>     % alpha2
>     axis_angle = atan(axis(2)/axis(1));
> ```

You generally never want to use atan when you can use atan2. atan2 uses sign to give you the proper quadrant.

---

_[matlab/project.m, line 33 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMXyO3AbwceS_Dr60:-KVzMXyO3AbwceS_Dr61:b-rq8lys) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L33)):_

> ``` objc
>     axis_angle = atan(axis(2)/axis(1));
> 
>     % This is used to make sure that angle is within [0,2pi)
> ```

"Wrap angle to [0,2pi)"

---

_[matlab/project.m, line 42 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzN8Dld4xyVFU9Cc1x:-KVzN8Dld4xyVFU9Cc1y:bb5nrnj) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L42)):_

> ``` objc
>     % alpha2
>     if((alpha1-axis_angle)*(alpha2-axis_angle)<0)
>        vertices_world(:,4)=[x+radius*cos(axis_angle); y+radius*sin(axis_angle)];
> ```

I understand the comment above, but it just applies to the `if` statement. Can you describe the action that is taken if the `if` statement evaluates to `true`? So this adds a column to `vertices_world`?

---

_[matlab/project.m, line 45 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOkeunrKlA_ZxAE28:-KVzOkeunrKlA_ZxAE29:bopdhyy) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L45)):_

> ``` objc
>     end
> 
>     % Since the back of the line also need to be checked, the oppoisite
> ```

What is the "back of the line"?
"need" -> "needs"
"oppoisite" -> "opposite"

---

_[matlab/project.m, line 52 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOwezj_Bzy7mlT7Jk:-KVzOwezj_Bzy7mlT7Jl:btbjpps) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L52)):_

> ``` objc
>     end
>     if((alpha1-axis_angle)*(alpha2-axis_angle)<0)
>        vertices_world(:,4)=[x+radius*cos(axis_angle); y+radius*sin(axis_angle)];
> ```

Why does this seem to overwrite the column you added before?

---

_[matlab/project.m, line 60 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzP3bSjTj8ADoOpiRJ:-KVzP3bSjTj8ADoOpiRK:bo3e7c6) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L60)):_

> ``` objc
> min_dot = realmax;
> max_dot = -realmax;
> [vertex_num, dim] = size(vertices_world);
> ```

FYI, since you're not using `dim`, you can just say `vertex_num = size(vertices_world,1)`.

---

_[matlab/project.m, line 62 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzQ9WyYLH3DWXAJ9tc:-KVzQ9WzqqVN8JZNMTbf:b-l1764u) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L62)):_

> ``` objc
> [vertex_num, dim] = size(vertices_world);
> for i = 1:vertex_num
>     value = axis*vertices_world(:,i);
> ```

It's safer to do `value = dot(axis, vertices_world(:,i))`. You could inadvertently do the outer product operation, and none of your `if` statements below would be the wiser.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Reviewed 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

_[matlab/project.m, line 48 at r5](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-cY7fjUShjMeeqz5E:-KW-cY7gX4aNn3ghgo0v:b-jwq69u) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/22f8cdd76b8f2f5ee9f268daebf1bdfbc7c80796/matlab/project.m#L48)):_

> ``` objc
>     end
> 
>     % checks the opposite direction of the line 
> ```

I'm still confused- what is the opposite direction of the line? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by yicheng0922** [comment]
Review status: 2 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

_[matlab/compute_box_vertices.m, line 9 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzLo79qTrQ-UypStU8:-KW-bPGjVkoHsUivTc-E:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/compute_box_vertices.m#L9)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> It's the "2D orientation" of the box, angle is not 2D!
> </details>
> Done.

---

_[matlab/compute_box_vertices.m, line 19 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzLVHDtkuosz_Qt6S9:-KW-bQ5J4K3yRtLl1nPz:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/compute_box_vertices.m#L19)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> Gerund issue.
> </details>
> Done.

---

_[matlab/project.m, line 27 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMN1yjXmg37i3wFjL:-KW-bREuZyXsIkqy4x5S:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L27)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> crosses -> crossing?
> </details>
> Done.

---

_[matlab/project.m, line 31 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMe5vrORp3F_Fsohr:-KW-bdtGeR9I5JGSPbYR:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L31)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> You generally never want to use atan when you can use atan2. atan2 uses sign to give you the proper quadrant.
> </details>
> Done.

---

_[matlab/project.m, line 33 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMXyO3AbwceS_Dr60:-KW-bdbdPv0BK2Kq3nTX:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L33)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> "Wrap angle to [0,2pi)"
> </details>
> Done.

---

_[matlab/project.m, line 42 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzN8Dld4xyVFU9Cc1x:-KW-beh0FN5wbZV9uWbe:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L42)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> I understand the comment above, but it just applies to the `if` statement. Can you describe the action that is taken if the `if` statement evaluates to `true`? So this adds a column to `vertices_world`?
> </details>
> Done.

---

_[matlab/project.m, line 62 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzQ9WyYLH3DWXAJ9tc:-KW-e4MZ7mNTPA5b61eL:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L62)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> It's safer to do `value = dot(axis, vertices_world(:,i))`. You could inadvertently do the outer product operation, and none of your `if` statements below would be the wiser.
> </details>
> Done.

---

_[matlab/project.m, line 48 at r5](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-cY7fjUShjMeeqz5E:-KW-ctDNv1Sju_DDUEec:b-y5636u) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/22f8cdd76b8f2f5ee9f268daebf1bdfbc7c80796/matlab/project.m#L48)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> I'm still confused- what is the opposite direction of the line? 
> </details>
> Maybe it is easier to explain over here because I can not figure out a concise wording for the comment. Currently I'm doing the check by checking if the orientation of the axis lies between the initial and the ending angle of the fan; however, this only checks half of  the line since it is actually just intersecting the ray starting from the center with the arc. This means that we also need to check ray that is anti-parallel. Make sense?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

_[matlab/project.m, line 31 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMe5vrORp3F_Fsohr:-KW-eZbPWDR_8r_DV5uT:bf5rfyu) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L31)):_
<details><summary>

<i>Previously, yicheng0922 wrote…</i></summary>



> Done.
> </details>
> Have you tried this? `atan2` takes two arguments, so I'd be surprised if this works...

---

_[matlab/project.m, line 48 at r5](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-cY7fjUShjMeeqz5E:-KW-elKNGYYRsLBnDK6C:bd0ks6z) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/22f8cdd76b8f2f5ee9f268daebf1bdfbc7c80796/matlab/project.m#L48)):_
<details><summary>

<i>Previously, yicheng0922 wrote…</i></summary>



> Maybe it is easier to explain over here because I can not figure out a concise wording for the comment. Currently I'm doing the check by checking if the orientation of the axis lies between the initial and the ending angle of the fan; however, this only checks half of  the line since it is actually just intersecting the ray starting from the center with the arc. This means that we also need to check ray that is anti-parallel. Make sense?
> </details>
> You don't necessarily need to make a comment concise. You can have multiple line comments. Why don't you clean up what you have above and just put it directly into the code?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Please submit the unit test for `project()` as well- I want to have some confidence that it works.

---

Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/project.m, line 31 at r6](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-mP2rf3xCpKsgb-pO:-KW-mP2rf3xCpKsgb-pP:bet56mz) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c666b69facc118c79d35b15b86783189a0719394/matlab/project.m#L31)):_

> ``` objc
>     % checking if the axis is pointing to a direction between alpha1 and
>     % alpha2
>     axis_angle = atan2(axis(2)/axis(1));
> ```

Have you verified that this call to `atan2()` actually works? It takes two arguments? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-:-KW-mjjYMHa8aFHEeQsa:b68sfjs)_

**Comment by yicheng0922** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/project.m, line 28 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMPcmD7xHB8P3wv7v:-KW-kuquX_2XxNCoKi-D:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L28)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> need -> needs"
> </details>
> Done.

---

_[matlab/project.m, line 31 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzMe5vrORp3F_Fsohr:-KW-pKJoopw8iazpjSbp:b-ybw447) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L31)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> Have you tried this? `atan2` takes two arguments, so I'd be surprised if this works...
> </details>
> Fixed now.

---

_[matlab/project.m, line 45 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOkeunrKlA_ZxAE28:-KW-mt3p3MOl7eDL4o1u:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L45)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> What is the "back of the line"?
> "need" -> "needs"
> "oppoisite" -> "opposite"
> </details>
> Done.

---

_[matlab/project.m, line 52 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOwezj_Bzy7mlT7Jk:-KW-pNPgTioWQkTNo1JK:bygikj8) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L52)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> Why does this seem to overwrite the column you added before?
> </details>
> Added explanation

---

_[matlab/project.m, line 48 at r5](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-cY7fjUShjMeeqz5E:-KW-mtU2vjMOViREyUmk:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/22f8cdd76b8f2f5ee9f268daebf1bdfbc7c80796/matlab/project.m#L48)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> You don't necessarily need to make a comment concise. You can have multiple line comments. Why don't you clean up what you have above and just put it directly into the code?
> </details>
> Done.

---

_[matlab/project.m, line 31 at r6](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-mP2rf3xCpKsgb-pO:-KW-p2gSvNLA0OG_kksj:b-tlxrkx) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c666b69facc118c79d35b15b86783189a0719394/matlab/project.m#L31)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> Have you verified that this call to `atan2()` actually works? It takes two arguments? 
> </details>
> Weird. I changed the  argument to (axis(1),axis(2))  but it is not showing properly...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by yicheng0922** [comment]
I made some change to the data structure so the unit test for project() is not working yet. I will push it back up once it is working.

---

Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-:-KW-qzK3aA2xUTiGYV12:b-5a4vf1)_

**Comment by edrumwri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[matlab/project.m, line 31 at r6](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-mP2rf3xCpKsgb-pO:-KW09Hw74KQtiuSUiZCV:bwdhddi) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c666b69facc118c79d35b15b86783189a0719394/matlab/project.m#L31)):_
<details><summary>

<i>Previously, yicheng0922 wrote…</i></summary>



> Weird. I changed the  argument to (axis(1),axis(2))  but it is not showing properly...
> </details>
> You should check the syntax. Usually it's axis(2), axis(1)- test and make sure that it works!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/project.m, line 52 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOwezj_Bzy7mlT7Jk:-KW0A17ZN6bH0K02-OHl:blbwajg) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L52)):_
<details><summary>

<i>Previously, yicheng0922 wrote…</i></summary>



> Added explanation
> </details>
> Ok, you just described an assertion: assert that the column size of vertices_world < 4 before you could possibly overwrite it.

---

_[matlab/project.m, line 54 at r7](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW0AFDoOlVTt4V4pdQ3:-KW0AFDoOlVTt4V4pdQ4:b-esedjw) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e59b99a7f5d5eeeaa9c10a9a93a664b9525f31e1/matlab/project.m#L54)):_

> ``` objc
>     % to do this, pi is subtracted from the angle and the same test is
>     % performed again
>     % note: this is not overwriting the previous vaule since only one of
> ```

vaule -> value

---

_[matlab/project.m, line 55 at r7](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW0AHi9OsqrQ9t3OyKk:-KW0AHi9OsqrQ9t3OyKl:b-40o3e3) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e59b99a7f5d5eeeaa9c10a9a93a664b9525f31e1/matlab/project.m#L55)):_

> ``` objc
>     % performed again
>     % note: this is not overwriting the previous vaule since only one of
>     % the two if condition can be true as long as all the fan shape are
> ```

condition -> conditions
shape -> shapes

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by yicheng0922** [comment]
The  unit test is now added

---

Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/project.m, line 52 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOwezj_Bzy7mlT7Jk:-KW1L_BbmhFJ2ia0YSZX:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L52)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> Ok, you just described an assertion: assert that the column size of vertices_world < 4 before you could possibly overwrite it.
> </details>
> Done.

---

_[matlab/project.m, line 31 at r6](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW-mP2rf3xCpKsgb-pO:-KW1LXbFENYYhcnThD2X:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c666b69facc118c79d35b15b86783189a0719394/matlab/project.m#L31)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> You should check the syntax. Usually it's axis(2), axis(1)- test and make sure that it works!
> </details>
> Done.

---

_[matlab/project.m, line 54 at r7](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW0AFDoOlVTt4V4pdQ3:-KW1LXwpDlZdI7HpVnSJ:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e59b99a7f5d5eeeaa9c10a9a93a664b9525f31e1/matlab/project.m#L54)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> vaule -> value
> </details>
> Done.

---

_[matlab/project.m, line 55 at r7](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW0AHi9OsqrQ9t3OyKk:-KW1LYxDUL2B8ozcuZ3d:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/e59b99a7f5d5eeeaa9c10a9a93a664b9525f31e1/matlab/project.m#L55)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> condition -> conditions
> shape -> shapes
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-:-KW1Lau_rFxXC3yyws3I:bfpiy3i)_

**Comment by edrumwri** [comment]
FYI, almost there!

---

Reviewed 1 of 2 files at r8.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/project.m, line 52 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOwezj_Bzy7mlT7Jk:-KW3J3ueluuwzBogu7A9:bx59hlw) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L52)):_
<details><summary>

<i>Previously, yicheng0922 wrote…</i></summary>



> Done.
> </details>
> That's not quite right- you want to assert that the number of _columns_ is fewer than 4. So it should look like `assert(size(vertices_world,2) < 4)`.

---

_[matlab/unit_test_project.m, line 15 at r8](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW3JSmyQJiiXnutkJ6r:-KW3JSmyQJiiXnutkJ6s:br9lhiy) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/91953744fc4a5f89184fb359c09cf37d2e44e998/matlab/unit_test_project.m#L15)):_

> ``` objc
> 
> 
> % this test for projecting a box onto an axis
> ```

this test _is_ for

---

_[matlab/unit_test_project.m, line 21 at r8](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW3J_TZ-uBM4kCl3GXz:-KW3J_TZ-uBM4kCl3GY-:bn55p1i) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/91953744fc4a5f89184fb359c09cf37d2e44e998/matlab/unit_test_project.m#L21)):_

> ``` objc
> % dot((0,0),(1,0)), where (0,0) is the bottom left vertex of the box 
> [min, max] = project(shape1, X_AXIS);
> assert((min==0 && max==4));
> ```

BTW this documentation is excellent.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-:-KW3JoiZjzoYXpQhPTe9:b-dq0pjq)_

**Comment by yicheng0922** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/project.m, line 52 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KVzOwezj_Bzy7mlT7Jk:-KW3xcFn-S1Bmn-XLu0_:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/c77cb97e0c0f6bb8e4561dea5c09eb159a1e31e0/matlab/project.m#L52)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> That's not quite right- you want to assert that the number of _columns_ is fewer than 4. So it should look like `assert(size(vertices_world,2) < 4)`.
> </details>
> Done.

---

_[matlab/unit_test_project.m, line 15 at r8](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-KW3JSmyQJiiXnutkJ6r:-KW3xdZxdbbhhf8Z443w:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/91953744fc4a5f89184fb359c09cf37d2e44e998/matlab/unit_test_project.m#L15)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> this test _is_ for
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3)_

**Comment by edrumwri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/3#-:-KW3zTgEwze1tjQBQyiL:bnfp4nl)_

**Pull request merged**
