### PR TITLE
Added obj_func

### PR DESCRIPTION
**Pull request by yicheng0922**
Added obj_func.m

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/optimized-compliance/1)

### CODE REVIEW

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[matlab/obj_func.m, line 2 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVf7bt-134vQVk0CZzT:-KVf7bt-134vQVk0CZzU:b-x65qnu) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/ebdad21b185e5fce5778ff716c2f0a09d0c841dc/matlab/obj_func.m#L2)):_

> ``` objc
> function [energy gradient] = obj_func( x )
> %OBJ_FUNC Summary of this function goes here
> ```

In your description of this function, please describe `x`. Also, you were supposed to replace the line "%OBJ_FUNC ..."

---

_[matlab/obj_func.m, line 6 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVf7jXl-CIUDRFqq3vn:-KVf7jXl-CIUDRFqq3vo:b-5m0rcu) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/ebdad21b185e5fce5778ff716c2f0a09d0c841dc/matlab/obj_func.m#L6)):_

> ``` objc
> % formula E = 1/2kd^2 where d is the amound of deforming.
> %   Detailed explanation goes here
>    spring_num1 = 23;
> ```

'23' and '20' are what we call "magic numbers". See https://en.wikipedia.org/wiki/Magic_number_(programming).
I think you're using these numbers because you're using 43 springs with two different spring constants. But I can't be sure. In any case, you want this code to be able to work with variable numbers of springs and spring constants.

---

_[matlab/obj_func.m, line 21 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVf8BnHTwIACocxGEdt:-KVf8BnHTwIACocxGEdu:b9gkrzu) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/ebdad21b185e5fce5778ff716c2f0a09d0c841dc/matlab/obj_func.m#L21)):_

> ``` objc
> 
> 
>    energy
> ```

Add a TODO comment to remove this output.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1)_

**Comment by yicheng0922** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[matlab/obj_func.m, line 1 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVg5tGZn-XKQZpZPYIk:-KVg5tG_SWqCRjddnXX7:bqzxezd) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/b0d850aeae062854cea562a49bcbac94d6673520/matlab/obj_func.m#L1)):_

> ``` objc
> function [energy gradient] = obj_func( x, spring_num1, spring_num2, k1, k2)
> ```

Moved constant to the parameters to make the code working with other spring constant and spring numbers

---

_[matlab/obj_func.m, line 4 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVg6CQIuTRJrEMaYZiM:-KVg6CQIuTRJrEMaYZiN:b-bvrcr5) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/b0d850aeae062854cea562a49bcbac94d6673520/matlab/obj_func.m#L4)):_

> ``` objc
> % the objectve function calculates the sum of potential energy by the
> % formula E = 1/2kd^2 where d is the diplacement of the spring end.
> % input: 
> ```

Added description of the input parameters

---

_[matlab/obj_func.m, line 31 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVg6JjMj_BHqBS1VxKh:-KVg6JjMj_BHqBS1VxKi:boavssq) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/b0d850aeae062854cea562a49bcbac94d6673520/matlab/obj_func.m#L31)):_

> ``` objc
>    end
> 
> %TODO: remove the output
> ```

Added TODO comment

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1)_

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

_[matlab/obj_func.m, line 10 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVgH-pymZLOQBNn26Z8:-KVgH-pzGb9I7S9zzQfz:b-esp9y4) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/b0d850aeae062854cea562a49bcbac94d6673520/matlab/obj_func.m#L10)):_

> ``` objc
> %       x(spring_num1+1:spring_num1+spring_num2): displacement of all springs 
> %                       from shape 2
> % spring_num1: The spring number from shape 1
> ```

Do you mean the number of springs?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-:-KVgHr6mrq6rnTujpOOk:bnfp4nl)_

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-:-KVgPdabaSMdwzfQ6lkj:bnfp4nl)_

**Comment by yicheng0922** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[matlab/obj_func.m, line 2 at r1](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVf7bt-134vQVk0CZzT:-KVgPYsPQiH2483w7_qe:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/ebdad21b185e5fce5778ff716c2f0a09d0c841dc/matlab/obj_func.m#L2)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> In your description of this function, please describe `x`. Also, you were supposed to replace the line "%OBJ_FUNC ..."
> </details>
> Done.

---

_[matlab/obj_func.m, line 10 at r3](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1#-KVgH-pymZLOQBNn26Z8:-KVgPYBVGX_tAzS9ujHL:b-896fix) ([raw file](https://github.com/edrumwri/optimized-compliance/blob/b0d850aeae062854cea562a49bcbac94d6673520/matlab/obj_func.m#L10)):_
<details><summary>

<i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>



> Do you mean the number of springs?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1)_

**Comment by yicheng0922** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/optimized-compliance/1)_

**Pull request merged**
